# Author puneetsd

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - cdk deploy --require-approval never --verbose
